numpatches: 100
startrev: "981bcfe73738" #"7ac88abc3c57" #"981bcfe73738" #"d03b538b6b41" #"d2218beee052" # #"48cc597db296"
outputdir: "C:/tmp/"
analysisbranch: "mozilla-inbound"
hg_analysisbranch: "integration/mozilla-inbound" # This may sometimes be different from `analysisbranch`
seta_suites: ["mochitest", "xpcshell"]
platform_prefix: "test-linux64/"

mochitest_tc_task_rev: "dcb3a3ba9065"
mochitest_tc_task_branch: "try"
xpcshell_tc_task_rev: "6369d1c6526b"
xpcshell_tc_task_branch: "try"