level: "file"
merge_line_diffs: False

jsvm_data: "C:/Users/greg/Documents/mozwork/coco-tools/jsvm_vs_jsdcov_2/jsvm_data/"
jsvm_baseline_data: C:/Users/greg/Documents/mozwork/coco-tools/jsvm_vs_jsdcov_2/baseline_data/jsvm/"

jsdcov_taskid: "Uh0v_-MLSsy5zJvurKHelQ"
jsdcov_baseline_taskid: "J6-a3OXaSO-pQKzATy6YIg"

chrome_map: "C:/Users/greg/Documents/mozwork/coco-tools/jsvm_vs_jsdcov_2/chrome-map.json"
outputdir : "C:/Users/greg/Documents/mozwork/coco-tools/jsvm_vs_jsdcov_2/results/"