per_test_dir: "/home/sparky/Documents/tmp/NKACHvgaT0uV-VESWcvVdg/"  #"/home/sparky/Documents/tmp/IOw6KhpsTbCXQrT2IS_jDQ/" #C:/Users/greg/Documents/mozwork/coco-tools/jsvm_vs_jsdcov_2/" #"C:/Users/greg/Documents/mozwork/coco-tools/jsvm_vs_jsdcov_2/jsdcov_data" #"C:/Users/greg/Documents/mozwork/coco-tools/jsvm_vs_jsdcov_2/"

sources: ["."] #"toolkit/content/editMenuOverlay.js"]
filetype: "pertestreport" # "jsdcov", "lcov", "pertestreport", "std-ptc-format"
delay: 0
outputdir: Null
show_src_coverage: False

chrome_map: "/home/sparky/Documents/tmp/NKACHvgaT0uV-VESWcvVdg/chrome-map.json"

test_files: ["about/browser_aboutCertError"]
