per_test_dir: "/home/sparky/Documents/tmp/PMfgzRH9TOaSmLqBWPFOCg/"  #"/home/sparky/Documents/tmp/IOw6KhpsTbCXQrT2IS_jDQ/" #C:/Users/greg/Documents/mozwork/coco-tools/jsvm_vs_jsdcov_2/" #"C:/Users/greg/Documents/mozwork/coco-tools/jsvm_vs_jsdcov_2/jsdcov_data" #"C:/Users/greg/Documents/mozwork/coco-tools/jsvm_vs_jsdcov_2/"
test_files: [
    "methodDetails-attribute.https.html", 
    "idlharness.tentative.any.sharedworker.html", 
    "meshgradient-basic-001.svg", 
    "1304353-text-global-composite-op-1.html", 
    "tall--32px-auto--nonpercent-width-nonpercent-height.html", 
    "idlharness.window.html", 
    "viewport-units-css2-001.html", 
    "string-compilation-integrity-classic.sub.html", 
    "interactability.py", 
    "icon-blocked.sub.html", 
    "shadow-rules.html", 
    "all-prop-initial-xml.html", 
    "autoplay-allowed-by-feature-policy.https.sub.html", 
    "bailout-exception-vs-return-origin.sub.window.html", 
    "audio_loop_base.html", 
    "fragid-shadow-3.html", 
    "deferred-anchor.xhtml", 
    "1425243-1.html", 
    "idlharness.window.html", 
    "RTCPeerConnection-track-stats.https.html", 
    "bold_namespace.html", 
    "slots-fallback-in-document.html", 
    "1474722.html", 
    "forced-bg-color-outside-visible-region.html", 
    "idlharness.window.html", 
    "2d.text.draw.baseline.alphabetic.html", 
    "outline-013.html", 
    "test_load_file.py", 
    "video_008.htm", 
    "accept.py", 
    "idlharness.window.html", 
    "mask-image-url-remote-mask.html", 
    "failure.html", 
    "registered-property-computation.html", 
    "treetwisty-svg-context-paint-1.xul", 
    "input-focus.html", 
    "border-image-019.xht", 
    "border-image-018.xht", 
    "box-sizing-minmax-width.html", 
    "pipe-through.dedicatedworker.html", 
    "webkit-text-stroke-property-002.html", 
    "legend-position-relative.html", 
    "response-static-redirect.html", 
    "img-src-self-unique-origin.html", 
    "name-tests.html", 
    "stream-safe-creation.any.worker.html", 
    "idlharness.any.worker.html", 
    "constructor-convert-all-arguments.js", 
    "mask-composite-1c.html", 
    "contain-paint-size-001.html", 
    "idlharness.https.window.html", 
    "createImageBitmap-invalid-args.html", 
    "border-image-017.xht", 
    "targeting.html", 
    "general-tests.html", 
    "perf_reftest", 
    "selection.html", 
    "contain-layout-ink-overflow-013.html", 
    "2d.path.arc.angle.2.html", 
    "frame-src-self-unique-origin.html", 
    "bounds.py", 
    "close.py", 
    "color-stops-parsing.html", 
    "element-request-fullscreen-active-document.html", 
    "interfaces.html", 
    "006.html", 
    "fetch-destination-no-load-event.https.html", 
    "RTCRtpTransceiver.https.html", 
    "RTCDTMFSender-ontonechange-long.https.html", 
    "border-image-020.xht", 
    "open-features-non-integer-screeny.html", 
    "user_prompts.py", 
    "fetch-destination.https.html", 
    "idlharness.any.sharedworker.html", 
    "idlharness.https.any.serviceworker.html", 
    "getter.html", 
    "properties-value-inherit-001.html", 
    "short.mp4.lastframe.html", 
    "class-id-attr-selector-invalidation-01.html", 
    "468263-2.html", 
    "user_prompts.py", 
    "testname", 
    "idlharness.window.html", 
    "large.https.html", 
    "img-and-image-1.html", 
    "dialog.html", 
    "mix-blend-mode-parent-element-overflow-scroll.html", 
    "spv-only-sent-to-initiator.sub.html", 
    "allowpaymentrequest-attribute-cross-origin-bc-containers.https.html", 
    "ImageCapture-creation.https.html", 
    "charset-03.html", 
    "webkit-pseudo-element.html", 
    "mask-opacity-1e.html"
]
sources: ["."] #"toolkit/content/editMenuOverlay.js"]
filetype: "pertestreport" # "jsdcov", "lcov", "pertestreport", "std-ptc-format"
delay: 0
outputdir: Null
show_src_coverage: False

chrome_map: "/home/sparky/Documents/tmp/PMfgzRH9TOaSmLqBWPFOCg/chrome-map.json"
