per_test_dir: "C:/Users/greg/Downloads/jsdcov_artifacts(17)" #C:/Users/greg/Documents/mozwork/coco-tools/jsvm_vs_jsdcov_2/" #"C:/Users/greg/Documents/mozwork/coco-tools/jsvm_vs_jsdcov_2/jsdcov_data" #"C:/Users/greg/Documents/mozwork/coco-tools/jsvm_vs_jsdcov_2/"
test_files: [".xml"]
sources: [".xul" ] #"toolkit/content/editMenuOverlay.js"]
filetype: "jsdcov" # "jsdcov", "lcov", "pertestreport"
delay: 5

chrome_map: "C:/Users/greg/Documents/mozwork/coco-tools/jsvm_vs_jsdcov_2/chrome-map.json"
