outputdir: "/home/sparky/Documents/tmp/"
task_group_id: "PMfgzRH9TOaSmLqBWPFOCg"
test_suites_list: ["build"]
pattern_match_suites: True
artifact_to_get: "chrome-map"
unzip_artifact: False
download_failures: True