numpatches: 115
startrev: "981bcfe73738" #"7ac88abc3c57" #"981bcfe73738" #"d03b538b6b41" #"d2218beee052" # #"48cc597db296"
outputdir: "/home/sparky/Documents/tmp/"
analysisbranch: "mozilla-inbound"

# For each branch in the given changesets, specify the HG repository i.e. mozilla-inbound -> integration/mozilla-inbound
hg_analysisbranch:
    mozilla-inbound: "integration/mozilla-inbound" # This may sometimes be different from `analysisbranch`
    autoland: "integration/autoland"

# This must be a list of CSV files
# with the same format as sample_csv.csv:
#   (fixed_by_revision, job_name, repo, test_fixed)
changesets: [
    '/home/sparky/Downloads/all_tests_fixed_by_commit_no_duplicates.csv'
]

mochitest_tc_task_rev: "dcb3a3ba9065"
mochitest_tc_task_branch: "try"
xpcshell_tc_task_rev: "6369d1c6526b"
xpcshell_tc_task_branch: "try"