outputdir: "/home/sparky/Documents/tmp/"
task_id: "QueDApG0QkiryJCLs5IKBg" # Get's the group from task details
test_suites_list: ["test-coverage"]
pattern_match_suites: True
artifact_to_get: "per-test"
unzip_artifact: True
download_failures: True