numpatches: 200
startrev: "d03b538b6b41" #"48cc597db296"
outputdir: "C:/tmp/"
analysisbranch: "mozilla-central"

mochitest_tc_task_rev: "dcb3a3ba9065"
mochitest_tc_task_branch: "try"
xpcshell_tc_task_rev: "6369d1c6526b"
xpcshell_tc_task_branch: "try"

analyze_files_with_missing_tests: False

check_against_seta: True
seta_suites: ["mochitest", "xpcshell"]
platform_prefix: "test-linux64/"